-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 15:47:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema campoEscuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema campoEscuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campoEscuela` DEFAULT CHARACTER SET utf8 ;
USE `campoEscuela` ;

-- -----------------------------------------------------
-- Table `campoEscuela`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(65) NOT NULL,
  `apellidos` VARCHAR(75) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `cargo` ENUM('0', '1') NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `password2` VARCHAR(200) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`incidentes` (
  `idincidentes` INT NOT NULL AUTO_INCREMENT,
  `descripcionInci` VARCHAR(250) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` ENUM('0', '1') NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idincidentes`),
  INDEX `idusuarios_idx8` (`id_usuario` ASC),
  CONSTRAINT `idusuarios8`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `idusuarios_idx1` (`id_usuario` ASC),
  CONSTRAINT `idusuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`donaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`donaciones` (
  `iddonaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `donante` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`iddonaciones`),
  INDEX `idusuarios_idx5` (`id_usuario` ASC),
  CONSTRAINT `idusuarios5`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`capacitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`capacitaciones` (
  `idcapacitaciones` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `nombreGrupo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `encargado` VARCHAR(45) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idcapacitaciones`),
  INDEX `idusuarios_idx4` (`id_usuario` ASC),
  CONSTRAINT `idusuarios4`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombrecate` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `nombreprod` VARCHAR(60) NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `unidaddemedida` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  `idcategorias` INT NOT NULL,
  PRIMARY KEY (`idinventario`),
  INDEX `idusuarios_idx6` (`id_usuario` ASC),
  INDEX `idcategorias_idx` (`idcategorias` ASC),
  CONSTRAINT `idusuarios6`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcategorias`
    FOREIGN KEY (`idcategorias`)
    REFERENCES `campoEscuela`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`kardex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`kardex` (
  `idkardex` INT NOT NULL AUTO_INCREMENT,
  `entrada` DECIMAL(10,2) NOT NULL,
  `salida` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `saldoanterior` DECIMAL(10,2) NOT NULL,
  `idinventario` INT NOT NULL,
  PRIMARY KEY (`idkardex`),
  INDEX `idinventario_idx` (`idinventario` ASC),
  CONSTRAINT `idinventario1`
    FOREIGN KEY (`idinventario`)
    REFERENCES `campoEscuela`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`perdidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`perdidas` (
  `idperdidas` INT NOT NULL AUTO_INCREMENT,
  `nombreProduc` VARCHAR(45) NOT NULL,
  `cantidad` TINYINT(2) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precioProduc` DECIMAL(10,2) NOT NULL,
  `mes` TINYINT(2) NOT NULL,
  `año` SMALLINT(4) NOT NULL,
  `unidadDelProduc` VARCHAR(45) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idperdidas`),
  INDEX `idusuarios_idx3` (`id_usuario` ASC),
  CONSTRAINT `idusuarios3`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `fechaventa` DATETIME NOT NULL,
  `preciounit` DECIMAL(6,2) NOT NULL,
  `cantidadprod` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `idinventario` INT NOT NULL,
  PRIMARY KEY (`idventas`),
  INDEX `idusuarios_idx7` (`id_usuario` ASC),
  INDEX `idinventario_idx` (`idinventario` ASC),
  CONSTRAINT `idusuarios7`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idinventario2`
    FOREIGN KEY (`idinventario`)
    REFERENCES `campoEscuela`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`partidas` (
  `idpartidas` INT NOT NULL AUTO_INCREMENT,
  `nombrepartida` VARCHAR(150) NOT NULL,
  `responsable` VARCHAR(50) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idpartidas`),
  INDEX `idusuarios_idx9` (`id_usuario` ASC),
  CONSTRAINT `idusuarios9`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`permisos` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`usuario_permiso` (
  `id_usuario_permisos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `idpermiso` INT NOT NULL,
  PRIMARY KEY (`id_usuario_permisos`),
  INDEX `idpermiso_idx` (`idpermiso` ASC),
  INDEX `idusuarios10_idx` (`id_usuario` ASC),
  CONSTRAINT `idpermiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `campoEscuela`.`permisos` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuarios10`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`detallepedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`detallepedidos` (
  `iddetallepedidos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NOT NULL,
  `cantidad` TINYINT(2) NOT NULL,
  `unidadmedida` VARCHAR(45) NOT NULL,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `precioUnitario` DECIMAL(10,2) NOT NULL,
  `precioTotal` DECIMAL(10,2) NOT NULL,
  `idpedidos` INT NOT NULL,
  PRIMARY KEY (`iddetallepedidos`),
  INDEX `idpedidos_idx` (`idpedidos` ASC),
  CONSTRAINT `idpedidos`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `campoEscuela`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`detallecapacitados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`detallecapacitados` (
  `iddetallecapacitaciones` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `idcapacitaciones` INT NOT NULL,
  PRIMARY KEY (`iddetallecapacitaciones`),
  INDEX `idcapacitaciones_idx` (`idcapacitaciones` ASC),
  CONSTRAINT `idcapacitaciones`
    FOREIGN KEY (`idcapacitaciones`)
    REFERENCES `campoEscuela`.`capacitaciones` (`idcapacitaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`cuentas` (
  `idcuentas` INT NOT NULL AUTO_INCREMENT,
  `idpartida` INT NOT NULL,
  `fechaInicio` DATETIME NOT NULL,
  `fechaFin` DATETIME NOT NULL,
  `IndicadorLogrado` VARCHAR(100) NOT NULL,
  `actGeneral` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcuentas`),
  INDEX `idpartida_idx` (`idpartida` ASC),
  CONSTRAINT `idpartida`
    FOREIGN KEY (`idpartida`)
    REFERENCES `campoEscuela`.`partidas` (`idpartidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`actividadesEspecificas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`actividadesEspecificas` (
  `idactividades` INT NOT NULL AUTO_INCREMENT,
  `idcuentas` INT NOT NULL,
  `actespecifica` VARCHAR(100) NOT NULL,
  `Racademico` VARCHAR(50) NULL,
  `Rtecnico` VARCHAR(50) NULL,
  `Rfinanciero` DECIMAL(10,2) NULL,
  `RInfraestructura` VARCHAR(150) NULL,
  PRIMARY KEY (`idactividades`),
  INDEX `idcuenta_idx` (`idcuentas` ASC),
  CONSTRAINT `idcuenta`
    FOREIGN KEY (`idcuentas`)
    REFERENCES `campoEscuela`.`cuentas` (`idcuentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`historial` (
  `idhistorial` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `accion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhistorial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`gasto` (
  `idgasto` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idgasto`),
  INDEX `idusuarios_idx2` (`id_usuario` ASC),
  CONSTRAINT `idusuarios2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `campoEscuela`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campoEscuela`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campoEscuela`.`insumo` (
  `idInsumo` INT NOT NULL AUTO_INCREMENT,
  `cantidad` TINYINT(2) NOT NULL,
  `unidadMedida` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `idpedido` INT NOT NULL,
  PRIMARY KEY (`idInsumo`),
  INDEX `idpedido_idx` (`idpedido` ASC),
  CONSTRAINT `idpedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `campoEscuela`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
